[I 2025-02-08 14:22:31.869 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-02-08 14:22:31.874 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-02-08 14:22:31.878 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-02-08 14:22:31.882 ServerApp] notebook | extension was successfully linked.
[I 2025-02-08 14:22:31.884 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2025-02-08 14:22:32.589 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-02-08 14:22:32.636 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-02-08 14:22:32.642 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-02-08 14:22:32.645 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-02-08 14:22:32.648 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/site-packages/jupyterlab
[I 2025-02-08 14:22:32.649 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2025-02-08 14:22:32.651 LabApp] Extension Manager is 'pypi'.
[I 2025-02-08 14:22:32.867 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-02-08 14:22:32.870 ServerApp] notebook | extension was successfully loaded.
[I 2025-02-08 14:22:32.871 ServerApp] Serving notebooks from local directory: /app/src/scripts
[I 2025-02-08 14:22:32.871 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-02-08 14:22:32.871 ServerApp] http://8bb609f56cb5:8888/tree?token=e61f46b619a7aac2ef4d75f2a5b3176487fc6f5cabaf4b54
[I 2025-02-08 14:22:32.871 ServerApp]     http://127.0.0.1:8888/tree?token=e61f46b619a7aac2ef4d75f2a5b3176487fc6f5cabaf4b54
[I 2025-02-08 14:22:32.871 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-02-08 14:22:32.874 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-15-open.html
    Or copy and paste one of these URLs:
        http://8bb609f56cb5:8888/tree?token=e61f46b619a7aac2ef4d75f2a5b3176487fc6f5cabaf4b54
        http://127.0.0.1:8888/tree?token=e61f46b619a7aac2ef4d75f2a5b3176487fc6f5cabaf4b54
[I 2025-02-08 14:22:32.888 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2025-02-08 14:25:26.057 ServerApp] 404 GET /hub/api (@192.168.144.1) 52.92ms referer=None
[I 2025-02-08 14:25:26.066 ServerApp] 302 GET / (@192.168.144.1) 0.59ms
[I 2025-02-08 14:25:26.075 JupyterNotebookApp] 302 GET /tree? (@192.168.144.1) 1.11ms
[I 2025-02-08 14:27:16.567 ServerApp] 302 GET / (@192.168.144.1) 0.46ms
[I 2025-02-08 14:27:16.620 JupyterNotebookApp] 302 GET /tree? (@192.168.144.1) 0.70ms
[W 2025-02-08 14:29:15.882 ServerApp] 404 GET /hub/api (@192.168.144.1) 1.69ms referer=None
[I 2025-02-08 14:29:15.886 ServerApp] 302 GET / (@192.168.144.1) 0.35ms
[I 2025-02-08 14:29:15.890 JupyterNotebookApp] 302 GET /tree? (@192.168.144.1) 0.49ms
[W 2025-02-08 14:29:17.779 ServerApp] 401 POST /login? (@192.168.144.1) 1.09ms referer=None
[W 2025-02-08 14:29:17.845 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-02-08 14:29:17.850 ServerApp] 403 GET /api/kernelspecs?1739024957840 (@192.168.144.1) 6.38ms referer=None
[W 2025-02-08 14:29:17.853 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-02-08 14:29:17.854 ServerApp] 403 GET /api/kernels?1739024957842 (@192.168.144.1) 2.50ms referer=None
[W 2025-02-08 14:29:17.854 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-02-08 14:29:17.855 ServerApp] 403 GET /api/kernels?1739024957844 (@192.168.144.1) 3.24ms referer=None
[W 2025-02-08 14:29:17.855 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-02-08 14:29:17.856 ServerApp] 403 GET /api/sessions?1739024957846 (@192.168.144.1) 3.93ms referer=None
[W 2025-02-08 14:29:17.879 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 784, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-02-08 14:29:17.880 ServerApp] 403 GET /api/kernelspecs?1739024957853 (@192.168.144.1) 1.52ms referer=None
[W 2025-02-08 14:29:17.882 ServerApp] 404 GET /hub/api (@192.168.144.1) 1.28ms referer=None
[I 2025-02-08 14:29:17.889 ServerApp] 302 GET / (@192.168.144.1) 0.45ms
[I 2025-02-08 14:29:17.893 JupyterNotebookApp] 302 GET /tree? (@192.168.144.1) 0.50ms
